import type { ReactNode } from 'react'
import { Sparkles, List, ListChecks, MessageCircleQuestion } from 'lucide-react'
import { cn } from '@renderer/lib/cn'
import { Skeleton } from '@renderer/components/Skeleton'
import type { Summary } from '@renderer/features/calls/types'

function SectionHeader({ icon, label }: { icon: ReactNode; label: string }): React.JSX.Element {
  return (
    <div className="mb-2 flex items-center gap-2">
      <span className="text-faint">{icon}</span>
      <h4 className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</h4>
    </div>
  )
}

function ListSection({
  icon,
  label,
  items,
  dotClass
}: {
  icon: ReactNode
  label: string
  items: string[]
  dotClass: string
}): React.JSX.Element {
  return (
    <div>
      <SectionHeader icon={icon} label={label} />
      <ul className="space-y-1.5">
        {items.map((item, index) => (
          <li key={index} className="flex gap-2.5 text-[15px] leading-relaxed text-ink">
            <span className={cn('mt-2 h-1.5 w-1.5 shrink-0 rounded-full', dotClass)} />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

/** Renders a structured AI summary. Shared by call and file summaries. */
export function SummaryView({ summary }: { summary: Summary }): React.JSX.Element {
  return (
    <div className="space-y-6">
      <div>
        <SectionHeader icon={<Sparkles className="h-4 w-4" />} label="Executive summary" />
        <p className="text-[15px] leading-relaxed text-ink">{summary.executive}</p>
      </div>
      {summary.keyPoints.length > 0 && (
        <ListSection
          icon={<List className="h-4 w-4" />}
          label="Key points"
          items={summary.keyPoints}
          dotClass="bg-accent"
        />
      )}
      {summary.actionItems.length > 0 && (
        <ListSection
          icon={<ListChecks className="h-4 w-4" />}
          label="Action items"
          items={summary.actionItems}
          dotClass="bg-positive"
        />
      )}
      {summary.questions.length > 0 && (
        <ListSection
          icon={<MessageCircleQuestion className="h-4 w-4" />}
          label="Questions & objections"
          items={summary.questions}
          dotClass="bg-warning"
        />
      )}
      <p className="text-[11px] text-faint">
        Generated by {summary.model} · {new Date(summary.createdAt).toLocaleString()}
      </p>
    </div>
  )
}

/** Animated placeholder shown while a summary is being generated. */
export function SummaryLoading({
  label = 'Summarizing with Claude…'
}: {
  label?: string
}): React.JSX.Element {
  return (
    <div>
      <div className="flex items-center gap-2.5 text-sm text-muted">
        <Sparkles className="h-4 w-4 animate-pulse text-accent" />
        <span>{label}</span>
      </div>
      <div className="mt-4 space-y-2.5">
        <Skeleton className="h-3 w-3/4" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-5/6" />
        <Skeleton className="h-3 w-2/3" />
      </div>
    </div>
  )
}
