#!/usr/bin/env node
// TRACKER STATUS — the Bug Tracker's headings stop carrying status; one line
// under each heading does; the index at the top is GENERATED from those lines;
// and this script REFUSES to write anything when a body disagrees with its
// status line.
//
// WHY. On 2026-09-05, 23 of 141 tracker headings (16%) misreported status —
// closures had been written into bodies, second entries, or "Last updated"
// lines while the heading kept saying OPEN, and the founder had been
// prioritising from the headings. Taxonomy species 88: a heading is a claim
// like any other and rots the same way. The founder's requirement: "either the
// heading stops carrying status or something checks them against each other
// … I don't want a process I have to remember."
//
// THE CONTRACT.
//   1. A heading is `## BUG-NNN — title` / `### BUG-NNN — title`. It carries NO
//      status word in a trailing parenthetical. (A non-status parenthetical,
//      e.g. "(Windows)", is fine.)
//   2. The FIRST non-blank line under a heading is the status line:
//        **Status:** FIXED · 2026-09-05 — free text
//      State ∈ OPEN | FIXED | CLOSED | DEFERRED | LOGGED. The date is when the
//      state was last decided.
//   3. Any dated closure marker deeper in the body (✅ …, CLOSED BY EVIDENCE,
//      **FIXED …, SHIPPED, LIVE-VERIFIED) that is LATER than the status line's
//      date while the state is still OPEN/DEFERRED/LOGGED is a disagreement.
//      The script exits 2, names every offender, and writes nothing.
//   4. The index between the markers at the top is regenerated on every write
//      from the status lines — it cannot disagree with the bodies.
//   5. An OPEN entry MAY carry a lane, between the date and the em-dash:
//        **Status:** OPEN · 2026-09-09 · WAITING-ON-FOUNDER — free text
//      Lane ∈ WAITING-ON-FOUNDER | WAITING-ON-DECISION | IN-FLIGHT | READY.
//      No lane is not an error — it is UNTRIAGED, which gets its own row and
//      its own count and is never folded into READY. A MISSPELT lane is an
//      error, named in one line, because a typo must not be able to disguise
//      itself as a deliberate "not yet triaged".
//
// USAGE.
//   node scripts/verification/tracker-status.mjs            # check + regenerate index (refuses on disagreement)
//   node scripts/verification/tracker-status.mjs --check    # read-only: exit 0 clean, 2 on disagreement
//   node scripts/verification/tracker-status.mjs --migrate  # one-time: strip heading status, add status lines, then check + index
//   --file <path>  overrides the tracker location (default: the vault's Bug Tracker.md)
//
// Runs whenever a session touches the tracker (a standing rule already), so
// the founder never has to remember it; the founder reads the index.
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

export const DEFAULT_TRACKER = 'C:/Users/User/Desktop/callrise ai project/04-Bugs/Bug Tracker.md'
export const STATES = ['OPEN', 'FIXED', 'CLOSED', 'DEFERRED', 'LOGGED']

/**
 * LANES — the second axis, added 2026-09-09 at the founder's request.
 *
 * WHY. The index said "37 OPEN" for three consecutive sessions. Both readings
 * of that are consistent with it — nothing closed, or three closed and three
 * found — and the founder could not tell which, nor which of the 37 were
 * theirs to move. Their words: *"Right now 37 OPEN mixes 'found ten minutes
 * ago' with 'waiting since July', and I can't tell whether the queue is
 * growing because you're finding things or because nothing's closing."*
 *
 * A count is not a metric until it distinguishes states someone would act on
 * differently. So OPEN is split by WHO IS BLOCKING, and movement is reported
 * beside the total.
 *
 * DECLARED, NOT DERIVED, and it cannot be otherwise: "blocked on the founder"
 * is a fact about the world, not about the text. So it is declared once per
 * entry, on the status line. The failure mode of a declared field is that it
 * falls behind — the same shape as CALL_RESTORE_RULES' literal — so the
 * absence of a lane is NEVER silently bucketed. It becomes UNTRIAGED, which
 * has its own row, its own count and its own instruction.
 */
export const LANES = {
  'WAITING-ON-FOUNDER': 'needs something only the founder can do — a machine, a call, a piece of data',
  'WAITING-ON-DECISION': 'needs a decision the founder has not made yet',
  'IN-FLIGHT': 'someone is working on it right now',
  READY: 'nothing is blocking it; nobody has started'
}
export const LANE_ORDER = ['WAITING-ON-FOUNDER', 'WAITING-ON-DECISION', 'IN-FLIGHT', 'READY']
/** Not a lane. The absence of one — counted and named so it cannot hide. */
export const UNTRIAGED = 'UNTRIAGED'

const INDEX_START = '<!-- tracker-index:start — GENERATED by scripts/verification/tracker-status.mjs; do not edit by hand -->'
const INDEX_END = '<!-- tracker-index:end -->'
const HEADING_RE = /^(#{2,3}) (BUG-(?:\d{3}|D))\b(.*)$/
// The lane is matched LOOSELY here and validated in check(). Matching it
// strictly would turn a typo ("READY " / "WAITNG-ON-FOUNDER") into "no status
// line under the heading", which refuses the whole write and names the wrong
// problem. A wrong lane should say so in one line.
const STATUS_LINE_RE = /^\*\*Status:\*\* (OPEN|FIXED|CLOSED|DEFERRED|LOGGED) · (\d{4}-\d{2}-\d{2})(?: · ([A-Z][A-Z-]{1,30}))?(?: — (.*))?$/
const DATE_RE = /\b(2026-\d{2}-\d{2})\b/g
// Closure MARKERS, not prose: uppercase FIXED/SHIPPED, the bold form, the ✅,
// the evidence stamp. Lower-case \"shipped\" in a sentence is not a closure — the
// first draft matched \"every install shipped since\" and closed BUG-137.
const CLOSURE_RE = /✅|CLOSED BY EVIDENCE|\*\*FIXED|\*\*Fixed\*\*|FIXED on (?:the )?branch|FIXED,? (?:shipped|in|on) |LIVE-VERIFIED|\bSHIPPED\b|shipped in v\d|\(FIXED\)/
const STATUS_WORDS_RE = /\b(OPEN|FIXED|CLOSED|SHIPPED|PART FIXED|PARTLY FIXED|PARTIALLY FIXED|NOT FIXED|LOGGED|DEFERRED|UNFIXED|WON'T FIX|WONTFIX)\b/i

/** Split the file into a preamble and entries, each entry = heading + body lines. */
export function parseTracker(text) {
  const lines = text.split('\n')
  const entries = []
  let preambleEnd = lines.length
  for (let i = 0; i < lines.length; i++) {
    const isHeading = /^#{1,6} /.test(lines[i])
    // Any heading closes the previous entry's body — including a non-BUG
    // section such as "## ✅ Recently fixed", whose bullets would otherwise
    // be read as the last entry's own closure lines (it happened: BUG-038).
    if (isHeading && entries.length && entries[entries.length - 1].end === lines.length) entries[entries.length - 1].end = i
    const m = HEADING_RE.exec(lines[i])
    if (!m) continue
    if (entries.length === 0) preambleEnd = i
    entries.push({ line: i, level: m[1].length, id: m[2], rest: m[3], end: lines.length })
  }
  for (const e of entries) e.body = lines.slice(e.line + 1, e.end)
  return { lines, preambleEnd, entries }
}

/** The trailing parenthetical of a heading, if it carries a status word. */
export function statusParenthetical(rest) {
  const m = /\s*\(([^()]*(?:\([^()]*\)[^()]*)*)\)\s*$/.exec(rest)
  if (!m) return null
  return STATUS_WORDS_RE.test(m[1]) ? { text: m[1], full: m[0] } : null
}

export function readStatusLine(body) {
  const idx = body.findIndex((l) => l.trim() !== '')
  if (idx === -1) return null
  const m = STATUS_LINE_RE.exec(body[idx].trim())
  return m ? { index: idx, state: m[1], date: m[2], lane: m[3] ?? null, note: m[4] ?? '' } : null
}

/** The latest date on a closure-looking line in the body (below the status line). */
export function latestClosureDate(body, fromIndex = 0) {
  let latest = null
  for (let i = fromIndex; i < body.length; i++) {
    const l = body[i]
    if (!CLOSURE_RE.test(l)) continue
    for (const d of l.match(DATE_RE) ?? []) if (!latest || d > latest) latest = d
  }
  return latest
}

function latestDateAnywhere(lines) {
  let latest = null
  for (const l of lines) for (const d of l.match(DATE_RE) ?? []) if (!latest || d > latest) latest = d
  return latest
}

/** Derive an initial state for an entry that has no canonical status line yet. */
export function deriveInitialStatus(entry) {
  const paren = statusParenthetical(entry.rest)
  const body = entry.body
  const legacy = body.find((l) => /^\s*-?\s*\*\*Status:\*\*/.test(l)) ?? ''
  const closure = latestClosureDate(body)
  const pick = (state, date, note) => ({ state, date: date ?? latestDateAnywhere(body) ?? '2026-08-01', note })
  const p = paren?.text ?? ''
  if (/HISTORICAL/i.test(entry.rest)) return pick('LOGGED', null, p || 'historical episode, not currently occurring')
  if (/CLOSED BY EVIDENCE/i.test(p)) return pick('CLOSED', (p.match(DATE_RE) ?? [])[0] ?? closure, p)
  if (/PART(?:LY|IALLY)? FIXED|PART FIXED/i.test(p)) return pick('OPEN', closure, p)
  if (/NOT FIXED|\bOPEN\b|UNFIXED/i.test(p) && !/FIXED on|SHIPPED/i.test(p)) return pick('OPEN', null, p)
  if (/LOGGED/i.test(p)) return pick('LOGGED', null, p)
  if (/DEFERRED|WON'T FIX|WONTFIX/i.test(p)) return pick('DEFERRED', null, p)
  if (/FIXED|SHIPPED/i.test(p)) return pick('FIXED', (p.match(DATE_RE) ?? [])[0] ?? closure, p)
  // The entry's own legacy status bullet is its declared status. A body
  // closure marker overrides it ONLY when it is LATER than the bullet's own
  // date (the stale-heading case this whole script exists for). A bullet that
  // says REOPENED / UNVERIFIED wins over any older closure below it.
  const legacyDate = (legacy.match(DATE_RE) ?? [])[0] ?? null
  const legacyOpen = /\[ \]/.test(legacy)
  const legacyReopened = /REOPENED|UNVERIFIED/i.test(legacy)
  // A closure marker line; one without a date borrows the body's latest date.
  const closureLines = body.filter((l) => CLOSURE_RE.test(l))
  const closureDate = closure ?? (closureLines.length ? latestDateAnywhere(body) : null)
  // A full-closure STAMP (written deliberately) beats an undated "[ ] Open";
  // a partial marker ("✅ FIX C BUILT") does not — the bullet is the entry's
  // own word and stays until something dated and later contradicts it.
  const stamp = closureLines.some((l) => /CLOSED BY EVIDENCE|FIXED on (?:the )?branch|LIVE-VERIFIED|\*\*FIXED/.test(l))
  const closureNewer = closureDate && (legacyDate ? closureDate > legacyDate : stamp)
  if (closureLines.length && (!legacyOpen || (closureNewer && !legacyReopened))) {
    if (closureLines.some((l) => /CLOSED BY EVIDENCE/.test(l))) return pick('CLOSED', closureDate, 'closed in the body; heading never updated')
    return pick('FIXED', closureDate, 'fixed per the body')
  }
  // legacy status bullet
  if (/\[x\]/i.test(legacy)) return pick('FIXED', (legacy.match(DATE_RE) ?? [])[0] ?? closure, legacy.replace(/^\s*-?\s*\*\*Status:\*\*\s*\[x\]\s*/i, '').replace(/\*\*/g, '').slice(0, 140))
  if (/\[ \]/.test(legacy)) {
    const note = legacy.replace(/^\s*-?\s*\*\*Status:\*\*\s*\[ \]\s*/, '').replace(/\*\*/g, '').slice(0, 140)
    if (/deferred|queued|blocked|decided against|scope note|not a defect|superseded/i.test(legacy)) return pick('DEFERRED', null, note)
    if (/logged/i.test(legacy)) return pick('LOGGED', null, note)
    return pick('OPEN', null, note)
  }
  return pick('OPEN', null, 'no status recorded before the migration')
}

/** One-time migration: strip status parentheticals, add canonical status lines,
 *  rename legacy status bullets to history so only ONE thing is called Status. */
export function migrate(text) {
  const { lines, entries } = parseTracker(text)
  const out = lines.slice()
  const changes = { headingsStripped: 0, statusLinesAdded: 0, legacyRenamed: 0 }
  // walk backwards so insertions do not shift earlier indexes
  for (let k = entries.length - 1; k >= 0; k--) {
    const e = entries[k]
    let rest = e.rest
    // A heading can carry MORE than one status parenthetical (BUG-109 had
    // "(OPEN, shipping in v1.3.3) (FIXED on branch 2026-09-05)"): strip until
    // none is left, counting the heading once.
    let stripped = false
    for (let paren = statusParenthetical(rest); paren; paren = statusParenthetical(rest)) {
      rest = rest.slice(0, rest.length - paren.full.length)
      stripped = true
    }
    if (stripped) changes.headingsStripped++
    out[e.line] = `${'#'.repeat(e.level)} ${e.id}${rest}`
    // rename legacy bullets inside the body
    for (let i = e.line + 1; i < e.end; i++) {
      if (/^\s*-?\s*\*\*Status:\*\*/.test(out[i]) && !STATUS_LINE_RE.test(out[i].trim())) {
        out[i] = out[i].replace(/\*\*Status:\*\*/, '**Status history:**')
        changes.legacyRenamed++
      }
    }
    if (!readStatusLine(e.body)) {
      const s = deriveInitialStatus(e)
      const note = (s.note || '').replace(/\s+/g, ' ').trim()
      out.splice(e.line + 1, 0, `**Status:** ${s.state} · ${s.date}${note ? ` — ${note}` : ''}`, '')
      changes.statusLinesAdded++
    }
  }
  return { text: out.join('\n'), changes }
}

/** The check: every heading clean, every entry with a status line, no body
 *  closure later than an OPEN-ish status. Returns the offenders. */
export function check(text) {
  const { entries } = parseTracker(text)
  const problems = []
  const statuses = []
  for (const e of entries) {
    const paren = statusParenthetical(e.rest)
    if (paren) problems.push(`${e.id} (line ${e.line + 1}): heading still carries a status parenthetical "(${paren.text})"`)
    const st = readStatusLine(e.body)
    if (!st) {
      problems.push(`${e.id} (line ${e.line + 1}): no status line directly under the heading`)
      continue
    }
    const closure = latestClosureDate(e.body, st.index + 1)
    if ((st.state === 'OPEN' || st.state === 'DEFERRED' || st.state === 'LOGGED') && closure && closure > st.date) {
      problems.push(`${e.id} (line ${e.line + 1}): status says ${st.state} · ${st.date} but the body has a closure dated ${closure} — decide which is true`)
    }
    // A misspelt lane is named, not silently dropped into UNTRIAGED: dropping
    // it would make a typo look like a deliberate "not yet triaged", which is
    // the difference between a queue that needs a decision and one that needs
    // a keystroke.
    if (st.lane && !LANES[st.lane]) {
      problems.push(`${e.id} (line ${e.line + 1}): unknown lane "${st.lane}" — use one of ${LANE_ORDER.join(', ')}, or leave it off`)
    }
    statuses.push({ id: e.id, level: e.level, line: e.line, state: st.state, date: st.date, lane: st.lane, title: e.rest.replace(/^\s*—\s*/, '').trim(), note: st.note })
  }
  return { problems, statuses }
}

/** Everything that is not still OPEN. Used for "closed" in the movement
 *  ledger: from the founder's side, DEFERRED and LOGGED have left the queue of
 *  things anyone is going to act on, so counting only FIXED would under-report
 *  movement and make the queue look stucker than it is. */
const IS_SETTLED = (state) => state !== 'OPEN'

/**
 * The movement ledger. Its own sidecar, deliberately NOT the existing
 * `.seen-ids.json` — that file belongs to another session's concurrent-edit
 * guard, and two tools writing one file is the hazard it was built to catch.
 */
export function movementPath(trackerFile) {
  return `${trackerFile}.movement.json`
}

export function readMovement(trackerFile) {
  try {
    const parsed = JSON.parse(readFileSync(movementPath(trackerFile), 'utf8'))
    return Array.isArray(parsed.runs) ? parsed : { runs: [] }
  } catch {
    return { runs: [] }
  }
}

/**
 * Compare two id→state maps. `opened` counts entries that did not exist before
 * OR were settled and are OPEN again (a reopen is movement in the wrong
 * direction and must not be invisible); `closed` counts OPEN → settled.
 */
export function diffRuns(before, after) {
  const opened = []
  const closed = []
  const reopened = []
  for (const [id, state] of Object.entries(after)) {
    const was = before[id]
    if (was === undefined) {
      if (state === 'OPEN') opened.push(id)
    } else if (IS_SETTLED(was) && state === 'OPEN') {
      reopened.push(id)
    } else if (was === 'OPEN' && IS_SETTLED(state)) {
      closed.push(id)
    }
  }
  return { opened, closed, reopened }
}

/** Append a run only when the id→state map actually CHANGED. The generator is
 *  run several times in one sitting; recording every run would bury the real
 *  movement under rows of zeroes. */
export function recordRun(trackerFile, statuses, nowIso, write = true) {
  const ledger = readMovement(trackerFile)
  const map = Object.fromEntries(statuses.map((s) => [s.id, s.state]))
  const last = ledger.runs[ledger.runs.length - 1]
  const changed = !last || JSON.stringify(last.ids) !== JSON.stringify(map)
  if (changed) {
    ledger.runs.push({ at: nowIso, ids: map })
    // Keep the ledger small enough to stay readable by hand; 60 changed runs
    // is months of work at this pace.
    if (ledger.runs.length > 60) ledger.runs = ledger.runs.slice(-60)
    if (write) writeFileSync(movementPath(trackerFile), JSON.stringify(ledger, null, 1), 'utf8')
  }
  return { ledger, changed, previous: last ? last.ids : null, current: map }
}

/** Roll the ledger up by day: opened / closed / net per date. */
export function movementByDay(ledger) {
  const byDay = new Map()
  for (let i = 1; i < ledger.runs.length; i++) {
    const d = ledger.runs[i].at.slice(0, 10)
    const { opened, closed, reopened } = diffRuns(ledger.runs[i - 1].ids, ledger.runs[i].ids)
    const row = byDay.get(d) ?? { opened: [], closed: [], reopened: [] }
    row.opened.push(...opened)
    row.closed.push(...closed)
    row.reopened.push(...reopened)
    byDay.set(d, row)
  }
  return [...byDay.entries()].sort((a, b) => (a[0] < b[0] ? 1 : -1))
}

export function renderIndex(statuses, movement = null) {
  const counts = Object.fromEntries(STATES.map((s) => [s, statuses.filter((x) => x.state === s).length]))
  const open = statuses.filter((x) => x.state === 'OPEN')
  const laneOf = (x) => (x.lane && LANES[x.lane] ? x.lane : UNTRIAGED)
  const laneCount = (lane) => open.filter((x) => laneOf(x) === lane).length
  const rows = []
  rows.push(INDEX_START)
  rows.push(`> **Index — ${statuses.length} entries: ${STATES.map((s) => `${counts[s]} ${s}`).join(' · ')}.** Generated from each entry's \`**Status:**\` line; a heading carries no status. Regenerate: \`node scripts/verification/tracker-status.mjs\`.`)
  rows.push('')

  // --- MOVEMENT ------------------------------------------------------------
  // A total on its own cannot distinguish "nothing closed" from "closed three,
  // found three". Both readings were consistent with three sessions of "37
  // OPEN", which is what made this section necessary.
  rows.push('### Movement')
  rows.push('')
  if (movement && movement.byDay.length) {
    rows.push('| day | opened | closed | net | what moved |')
    rows.push('|---|---|---|---|---|')
    for (const [day, r] of movement.byDay.slice(0, 14)) {
      const net = r.opened.length + r.reopened.length - r.closed.length
      const what = [
        ...r.closed.map((id) => `−${id}`),
        ...r.opened.map((id) => `+${id}`),
        ...r.reopened.map((id) => `↺${id}`)
      ].join(' ')
      rows.push(`| ${day} | ${r.opened.length} | ${r.closed.length} | ${net > 0 ? '+' : ''}${net} | ${what.slice(0, 150)} |`)
    }
    rows.push('')
  }
  if (movement) {
    rows.push(`*Recorded from ${movement.since}. Movement before that date is not in the ledger and is NOT reported as zero — it was never measured.* A reopen (↺) counts toward *opened*: it is movement, and in the wrong direction.`)
  } else {
    rows.push('*No movement recorded yet. This is an absence of measurement, not an absence of movement.*')
  }
  rows.push('')

  // The ledger above is true opened/closed, and it starts the day it was
  // built. This second table is DERIVED from data that already existed, so it
  // works backwards over the whole tracker — at the cost of a real limitation
  // that is stated rather than buried.
  const byDate = new Map()
  for (const x of statuses) {
    const row = byDate.get(x.date) ?? Object.fromEntries(STATES.map((s) => [s, 0]))
    row[x.state]++
    byDate.set(x.date, row)
  }
  const dates = [...byDate.keys()].sort().reverse().slice(0, 10)
  if (dates.length) {
    rows.push('**Where each entry\'s CURRENT status was set** — derived from the status dates, so it reaches back before the ledger.')
    rows.push('')
    rows.push(`| day | ${STATES.join(' | ')} |`)
    rows.push(`|---|${STATES.map(() => '---').join('|')}|`)
    for (const d of dates) rows.push(`| ${d} | ${STATES.map((s) => byDate.get(d)[s] || '').join(' | ')} |`)
    rows.push('')
    rows.push('*This is NOT opened-vs-closed.* It counts where each entry sits **now**, by the date that state was decided — so an entry opened in July and fixed today appears only under today, and a day\'s openings are invisible once they are closed. It answers "is anything being settled?" and cannot answer "how many were found?". The ledger above answers the second, from the day it started.')
    rows.push('')
  }

  // --- OPEN, SPLIT BY WHO IS BLOCKING --------------------------------------
  rows.push(`### OPEN (${open.length}) — by who is blocking`)
  rows.push('')
  rows.push('| lane | n | meaning |')
  rows.push('|---|---|---|')
  for (const lane of LANE_ORDER) rows.push(`| **${lane}** | ${laneCount(lane)} | ${LANES[lane]} |`)
  const untriaged = laneCount(UNTRIAGED)
  rows.push(`| **${UNTRIAGED}** | ${untriaged} | no lane on the status line — **not** a claim that it is ready |`)
  rows.push('')
  if (untriaged) {
    rows.push(`> **${untriaged} of ${open.length} open entries carry no lane.** Add one to the status line as \`**Status:** OPEN · <date> · READY — …\`. Until then they are counted here and nowhere else, deliberately: folding them into READY would make an untriaged queue look like a ready one.`)
    rows.push('')
  }
  for (const lane of [...LANE_ORDER, UNTRIAGED]) {
    const group = open.filter((x) => laneOf(x) === lane).sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.id < b.id ? 1 : -1))
    if (!group.length) continue
    rows.push(`**${lane} (${group.length})** — ${LANES[lane] ?? 'no lane declared'}`)
    rows.push('')
    // The note column exists for WAITING-ON-DECISION above all: a lane that
    // says "blocked on a decision" without saying WHICH decision moves the
    // question out of the tracker and into someone's memory — which is where
    // the 37-that-never-moved was already living.
    rows.push('| entry | since | title | status note |')
    rows.push('|---|---|---|---|')
    for (const x of group) {
      const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
      rows.push(`| [[${x.id}]] | ${x.date} | ${cell(x.title).slice(0, 100)} | ${cell(x.note).slice(0, 160)} |`)
    }
    rows.push('')
  }

  for (const state of STATES.filter((s) => s !== 'OPEN')) {
    const group = statuses.filter((x) => x.state === state).sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.id < b.id ? 1 : -1))
    if (!group.length) continue
    rows.push(`**${state} (${group.length})**`)
    rows.push('')
    rows.push('| entry | since | title |')
    rows.push('|---|---|---|')
    for (const x of group) rows.push(`| [[${x.id}]] | ${x.date} | ${x.title.replace(/\|/g, '\\|').slice(0, 110)} |`)
    rows.push('')
  }
  rows.push(INDEX_END)
  return rows.join('\n')
}

/** Insert or replace the index block right after the file's intro (before the first `---`). */
export function withIndex(text, statuses, movement = null) {
  const block = renderIndex(statuses, movement)
  const s = text.indexOf(INDEX_START)
  const e = text.indexOf(INDEX_END)
  if (s >= 0 && e > s) return text.slice(0, s) + block + text.slice(e + INDEX_END.length)
  const hr = text.indexOf('\n---\n')
  const at = hr >= 0 ? hr + 1 : 0
  return text.slice(0, at) + block + '\n\n' + text.slice(at)
}

export function main(argv = process.argv.slice(2)) {
  const fileIdx = argv.indexOf('--file')
  const file = fileIdx >= 0 ? argv[fileIdx + 1] : DEFAULT_TRACKER
  const mode = argv.includes('--migrate') ? 'migrate' : argv.includes('--check') ? 'check' : 'write'
  if (!existsSync(file)) {
    console.error(`tracker not found: ${file}`)
    return 1
  }
  let text = readFileSync(file, 'utf8')
  if (mode === 'migrate') {
    copyFileSync(file, `${file}.pre-migration.bak`)
    const r = migrate(text)
    text = r.text
    console.log(`migrated: ${r.changes.headingsStripped} headings stripped of status, ${r.changes.statusLinesAdded} status lines added, ${r.changes.legacyRenamed} legacy status bullets renamed to history`)
  }
  const { problems, statuses } = check(text)
  if (problems.length) {
    console.error(`REFUSING to write — ${problems.length} disagreement(s):`)
    for (const p of problems) console.error('  ' + p)
    if (mode === 'migrate') {
      // the migrated text is written to a sidecar so the offenders can be resolved by hand, never over the real file
      writeFileSync(`${file}.migrated-with-problems.md`, text, 'utf8')
      console.error(`migrated text saved beside the tracker as .migrated-with-problems.md; the tracker itself is untouched`)
    }
    return 2
  }
  const counts = STATES.map((s) => `${statuses.filter((x) => x.state === s).length} ${s}`).join(', ')
  if (mode === 'check') {
    console.log(`clean: ${statuses.length} entries — ${counts}`)
    return 0
  }
  // Record BEFORE rendering, so this run's own change is in the ledger the
  // index reports. The ledger is written first for the same reason: if the
  // tracker write then fails, the movement is still recorded, and a ledger
  // slightly ahead of the index is recoverable while one behind is a silently
  // lost day.
  const run = recordRun(file, statuses, new Date().toISOString())
  const byDay = movementByDay(run.ledger)
  const movement = { byDay, since: run.ledger.runs[0]?.at.slice(0, 10) ?? 'now' }
  const next = withIndex(text, statuses, movement)
  if (next !== readFileSync(file, 'utf8')) writeFileSync(file, next, 'utf8')
  const delta = run.previous ? diffRuns(run.previous, run.current) : null
  const moved = delta
    ? `; moved since the last recorded run: +${delta.opened.length} opened, -${delta.closed.length} closed, ${delta.reopened.length} reopened`
    : '; first recorded run — no movement to report yet'
  const open = statuses.filter((x) => x.state === 'OPEN')
  const untriaged = open.filter((x) => !(x.lane && LANES[x.lane])).length
  console.log(`written: ${statuses.length} entries — ${counts}${moved}`)
  console.log(`OPEN ${open.length}: ` + [...LANE_ORDER.map((l) => `${open.filter((x) => x.lane === l).length} ${l}`), `${untriaged} ${UNTRIAGED}`].join(', '))
  return 0
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exit(main())
}
